version: '3.1'

services:
  #  mysql:
  #    image: mysql:5.7
  #    restart: always
  #    ports:
  #      - 3306:3306
  #    volumes:
  #      - horarios:/var/lib/mysql
  #    environment:
  #      MYSQL_ROOT_PASSWORD: root
  #      MYSQL_DATABASE: horarios
  #      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  db:
    image: postgis/postgis:13-3.1-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass2021
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - horarios_postgres:/var/lib/postgresql/data
      - ./seed/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

volumes:
  #  horarios:
  #    driver: local
  horarios_postgres:
    driver: local

